# Use postgres/example user/password credentials
version: '3.1'

services:

  estrutura:
    build: .
    restart: on-failure
    command: npx prisma migrate dev --create-only
    ports:
      - 8085:3000
    depends_on:
      - db
    networks:
      - network-estrutura
    volumes:
      - ".:/app"
      - "nodemodule:/app/node_modules"
  db:
    image: postgres
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5439:5432
    networks:
      - network-estrutura

  adminer:
    image: adminer
    restart: on-failure
    ports:
      - 8080:8080
    networks:
      - network-estrutura


volumes:
  nodemodule: {}

networks:
  network-estrutura:
    driver: bridge